<div class="container-fluid">
    <div class="row">
        <div class="table-responsive">
            <table class="table table-bordered" id="table-tes">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama</th>
                        <th>HP</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>Bejo</td>
                        <td>90898709690879</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Bejo</td>
                        <td>90898709690879</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Bejo</td>
                        <td>90898709690879</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Bejo</td>
                        <td>90898709690879</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Bejo</td>
                        <td>90898709690879</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Bejo</td>
                        <td>90898709690879</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Bejo</td>
                        <td>90898709690879</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Bejo</td>
                        <td>90898709690879</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Bejo</td>
                        <td>90898709690879</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Bejo</td>
                        <td>90898709690879</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Bejo</td>
                        <td>90898709690879</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Bejo</td>
                        <td>90898709690879</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>